set(CMAKE_C_COMPILER /usr/bin/arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER /usr/bin/arm-linux-gnueabihf-g++)
set(CMAKE_LINKER /usr/bin/arm-linux-gnueabihf-ld)
# set(CMAKE_BUILD_TYPE Release)
# include("../../src/CMakeLists.txt")