set(CMAKE_C_COMPILER /usr/bin/mipsel-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER /usr/bin/mipsel-linux-gnu-g++)
set(CMAKE_LINKER /usr/bin/mipsel-linux-gnu-ld)
# set(CMAKE_BUILD_TYPE Release)
# include("../../src/CMakeLists.txt")